trainingInput:
  scaleTier: CUSTOM # BASIC | BASIC_GPU | STANDARD_1 | PREMIUM_1 | CUSTOM
  masterType: n1-highcpu-16
#  workerType: n1-highcpu-16
#    parameterServerType: n1-highmem-8
#    workerCount: 4
#    parameterServerCount: 1